from pydantic import BaseModel, Field, validator
from typing import Dict, List, Optional, Literal
from datetime import datetime

class TransportType(str):
    TCP = "tcp"
    TLS = "tls"

class MediaEncryption(str):
    DISABLED = "disabled"
    ALLOWED = "allowed"
    REQUIRED = "required"

class SIPTrunkCreate(BaseModel):
    phone_number: str = Field(..., description="E.164 format phone number (e.g., +15551234567)")
    label: str = Field(..., description="Friendly name for the trunk")
    outbound_address: str = Field(..., description="User's PBX hostname or IP (e.g., sip.telnyx.com)")
    inbound_transport: Literal["tcp", "tls"] = Field(default="tcp", description="Transport protocol for inbound calls")
    outbound_transport: Literal["tcp", "tls"] = Field(default="tcp", description="Transport protocol for outbound calls")
    inbound_media_encryption: Literal["disabled", "allowed", "required"] = Field(default="disabled")
    outbound_media_encryption: Literal["disabled", "allowed", "required"] = Field(default="disabled")
    auth_username: Optional[str] = Field(None, description="Digest authentication username")
    auth_password: Optional[str] = Field(None, description="Digest authentication password")
    custom_headers: Optional[Dict[str, str]] = Field(None, description="Custom SIP headers")
    assigned_agent_id: Optional[str] = Field(None, description="Agent ID to route calls to")

    @validator('phone_number')
    def validate_phone_number(cls, v):
        # Basic E.164 validation
        if not v.startswith('+'):
            raise ValueError('Phone number must be in E.164 format (start with +)')
        if not v[1:].isdigit():
            raise ValueError('Phone number must contain only digits after +')
        if len(v) < 8 or len(v) > 16:
            raise ValueError('Phone number length must be between 8 and 16 characters')
        return v

    @validator('outbound_address')
    def validate_outbound_address(cls, v):
        # Remove sip: prefix if present
        if v.startswith('sip:'):
            raise ValueError('Outbound address should be hostname/IP only, not a full SIP URI')
        return v

class SIPTrunkUpdate(BaseModel):
    label: Optional[str] = None
    outbound_address: Optional[str] = None
    inbound_transport: Optional[Literal["tcp", "tls"]] = None
    outbound_transport: Optional[Literal["tcp", "tls"]] = None
    inbound_media_encryption: Optional[Literal["disabled", "allowed", "required"]] = None
    outbound_media_encryption: Optional[Literal["disabled", "allowed", "required"]] = None
    auth_username: Optional[str] = None
    auth_password: Optional[str] = None
    custom_headers: Optional[Dict[str, str]] = None
    assigned_agent_id: Optional[str] = None
    is_active: Optional[bool] = None

class SIPTrunkResponse(BaseModel):
    id: str
    user_id: str
    phone_number: str
    label: str
    sip_domain: str  # Generated by us
    inbound_transport: str
    outbound_transport: str
    inbound_media_encryption: str
    outbound_media_encryption: str
    outbound_address: Optional[str] = None
    custom_headers: Optional[Dict[str, str]] = None
    auth_username: Optional[str] = None  # Password not included in response
    assigned_agent_id: Optional[str] = None
    is_active: bool
    # Connection status (ElevenLabs model)
    connection_status: str = "pending"  # pending, connected, disconnected, error
    last_connected_at: Optional[datetime] = None
    last_checked_at: Optional[datetime] = None
    error_message: Optional[str] = None
    created_at: datetime
    updated_at: datetime

    class Config:
        from_attributes = True
